### ISSUE TITLE
add filter for invoices. 

### ISSUE THREAD

**Issue by ErickRodriguezWize** [wizeline/ror-remotepayment-wizeline#12]
**Requirement** 

> Some Contractors needs to declare taxes once a year on their country. For this situation, they ask to be able to download finish invoices (process by finance's people) from an specific period of time. **Ex. All voices of year 2023**

What to do ? 

- Create a filter/query for invoices on a specific period of time. **(Ex. From January 2021 to June 2021).**

**Comment by XoCedillo** [comment]
tracked in [add filter for Invoices](https://github.com/wizeline/ror-remotepayment-wizeline/issues/29#)
#29
