### ISSUE TITLE
Create a module to render PDF 

### ISSUE THREAD

**Issue by ErickRodriguezWize** [wizeline/ror-remotepayment-wizeline#23]
**What to do?** 

- Create a module that create a Wicked PDF object with a html template (bytes). 
- Render the wicked pdf object and create 2 methods:
1. A method to send the Wicked PDF object as a response. 
2. A method to render directly to the browser the output of the Wicked PDF object generated. 

**Once you finish comment this issue with the following information:**

- On which branch did you pushed your commits?
- Additional information regarding to this ticket (installation, notes, warnings, observation, etc).

**Comment by XoCedillo** [comment]
Refactoring of the code must be done. Business logic should not be in controller a service and class folder must be created to handle this logic
