### ISSUE TITLE
Setup OAuth environment (installing gems, setting devs accounts).

### ISSUE THREAD

**Issue by vinfante** [wizeline/ror-remotepayment-wizeline#38]
**What to do?** 

- Install the required gems for **OAuth(google-id-token, google-apis-oauth2_v2').**
- Backend: create a pair of routes for login/logout. 
- Create controller to handle routes for login/logout. 
- Create helper module to declare some classes:

**Authenticator:** In charge of handling and validation of the id_token from Google, validations are done locally in the backend and remotely with the Google Api endpoint.

- Define authenticated_user? function to include the needed validations to decide if a user has authorization to proceed with the api call. 
- Add figaro configurations for the required ENV variables to exist in the project for the authentication. 
- Define Base JSON responses for success and fail requests responses for the login/logout.  

**Once you finish comment this issue with the following information:**

- On which branch did you pushed your commits?
- Additional information regarding to this ticket (installation, notes, warnings, observation, etc).

**Comment by ErickRodriguezWize** [comment]
PR accepted, closing ticket.
