### ISSUE TITLE
Add 'Role' field to the auth/callback response; rename 'data' json structure to 'user'

### ISSUE THREAD

**Issue by vinfante** [wizeline/ror-remotepayment-wizeline#55]
Add 'Role' field to the auth/callback response so the frontend know what dashboard to display after login

Role Field will contain the String name from the associated User's role

Update the returning json to name the 'data' field to 'user'

i.e.:
```
...
"user": {
...
"role": "Contractor",
...
}
...
```

cc: @fannypc11

**Comment by ErickRodriguezWize** [comment]
Approved PR that link too this issue
